### ISSUE TITLE
Unable to download pretrained model

### ISSUE THREAD

**Issue by AndssY** [yunyikristy/DualMind#1]
Thanks for the work you have done and the resources you have shared.

I attempted to download the pretrained model from the following link mentioned in your repository. Unfortunately, when I click on the link, it redirects me to the page I am already on, without providing access to the pretrained model files.Could you please provide an way to download the pretrained model or rectify the link shared in the repository?

Any assistance you can offer would be greatly appreciated. Thanks again for you for the resources you have shared.

**Comment by yaowei1024** [comment]
Hi, thanks for your interest in our work. 
Now, you can download checkpoints on huggingface repo.[DualMind](https://huggingface.co/Clumsy1/DualMind/)
